name: 'Dependency Review'

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    env:
      FIRST_COMMIT_SHA: 598ef863ac089ce3682f40d4abe55d21266594ea
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        with:
          head-ref: HEAD
          base-ref: "${{ env.FIRST_COMMIT_SHA }}"
          config-file: './.github/dependency-review-config.yml'
